### ISSUE TITLE
currentWeatherData.getCurrent().getRain() null and no getThreeHourLevel() method

### ISSUE THREAD

**Issue by pnoe** [Prominence/openweathermap-java-api#19]
Hi,
currentWeatherData.getCurrent().getRain() returns null when there is no rain
and
currentWeatherData.getCurrent().getRain().getThreeHourLevel() doesn't exist

Is this normal ?

Bye

**Comment by Prominence** [comment]
Hi!
1. `currentWeatherData.getCurrent().getRain() returns null when there is no rain`
I've not decided yet what is a preferable way to handle such cases. Probably it is better to return `Optional<Rain>` object instead of null. What are your proposals?

2. `currentWeatherData.getCurrent().getRain().getThreeHourLevel() doesn't exist`
As I can see, you are speaking about **OneCall** API. There is only `1h` field available for the rain and snow objects. Here is an official OpenWeatherMap docs: https://openweathermap.org/api/one-call-api#parameter

**Comment by pnoe** [comment]
Thank you for your quick answer.
1. I find it fine as it is. I was just wondering if I was missing something. I use CurrentWeatherData in a Thymeleaf template and the notation currentWeatherData.current.rain?.oneHourLevel with a "?" is fine with a null value.
2. Sorry I was mixing the two apis "Current Weather Data" and "One Call API" !

**Comment by Prominence** [comment]
There is differences between several API in some classes(`Rain`, `Snow`, `Temperature`, `AtmosphericPressure`, etc.). So I've decided to use different classes with the same name(but in different packages) to store data. This approach shouldn't let you await rain volume for 3h(for example) because of missing getters and fields when API isn't providing such data. That was my goal to disable possibility of doing something wrong by design.

Thanks for your feedback!
